<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VEDANT" ignored="0" name="Test(failed)" tests="7" failures="7" timestamp="09 Feb 2023 06:23:38 GMT" time="27.404" errors="0">
  <testcase name="createTask" time="11.169" classname="testNG.TestngtActiTime">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNG.TestngtActiTime.createTask(TestngtActiTime.java:22)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- createTask -->
  <testcase name="deleteTask" time="0.001" classname="testNG.TestngtActiTime">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNG.TestngtActiTime.deleteTask(TestngtActiTime.java:54)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- deleteTask -->
  <testcase name="countNames" time="3.519" classname="testNG.TestngErail">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNG.TestngErail.countNames(TestngErail.java:23)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- countNames -->
  <testcase name="f" time="7.814" classname="testNG.TestngSortable">
    <failure type="org.openqa.selenium.WebDriverException" message="java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:50677
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;VEDANT&amp;apos;, ip: &amp;apos;192.168.43.82&amp;apos;, os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_351&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:50677
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'VEDANT', ip: '192.168.43.82', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_351'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
at utilities.SeleniumUtility.setUp(SeleniumUtility.java:66)
at testNG.TestngSortable.f(TestngSortable.java:17)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:50677
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
... 29 more
Caused by: java.net.ConnectException: Connection refused: connect
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
... 49 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="modifyTask" time="0.0" classname="testNG.TestngVtiger">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNG.TestngVtiger.modifyTask(TestngVtiger.java:40)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- modifyTask -->
  <testcase name="createTask" time="4.836" classname="testNG.TestngVtiger">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNG.TestngVtiger.createTask(TestngVtiger.java:19)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- createTask -->
  <testcase name="deleteTask" time="0.002" classname="testNG.TestngVtiger">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNG.TestngVtiger.deleteTask(TestngVtiger.java:53)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- deleteTask -->
</testsuite> <!-- Test(failed) -->
